### ISSUE TITLE
Yarn 2 "Unrecognized or legacy configuration settings found" npmScopes and npmRegistries

### ISSUE THREAD

**Issue by ZachSaucier** [yarnpkg/berry#2306]
### Bug description
In a fresh install of yarn 2 in an otherwise empty project, I am getting an "Unrecognized or legacy configuration settings found" for my npmScopes and npmRegistries settings in my .yarnrc.yml file. Here are the contents of the file (with the token replaced):

```
yarnPath: ".yarn/releases/yarn-berry.cjs"
npmScopes:
	gsap:
		npmRegistryServer: "https://npm.greensock.com"
npmRegistries: 
	//npm.greensock.com:
		npmAlwaysAuth: true
		npmAuthToken: "TOKEN-GOES-HERE"
```

**What is the current behavior?**
Yarn errors at the `gsap` or `//npm.greensock.com:` lines (depending which one I put first in the file). It seems like I'm doing it correctly [according to the docs](https://yarnpkg.com/configuration/yarnrc#npmRegistries). Has something changed?

**What is the expected behavior?**
I expect it to install GSAP from the given private registry.

Using NPM I can install this by adding the following to my .npmrc file:

```
//npm.greensock.com/:_authToken=TOKEN-GOES-HERE
@gsap:registry=https://npm.greensock.com
```

and installing via `npm install gsap@npm:@gsap/business`

**Environment**

- Yarn v1 Version: `1.22.10` 
- OS and version: Catalina

**Comment by merceyz** [comment]
There was some issues with older versions and the global config, these have been fixed in later releases

**Comment by Smbkilla** [comment]
Hi,
I'm having the same issue when trying to upgrade to yarn 2
I've tried using the latest version with `yarn set version from sources` but i still get `"Unrecognized or legacy configuration settings found" npmScopes`

**Comment by merceyz** [comment]
I'd guess you have a `yarnPath` / `yarn-path` config in your global `.yarnrc.yml` / `.yarnrc` file pointing to an old version, try removing those

**Comment by Smbkilla** [comment]
Hi,

I don't think so. My `.yarnrc.yml` files point to `.yarn/releases/yarn-sources.cjs`, global ones don't have `yarnPath` config in them.
To make sure of that I've tested it in new WSL with all fresh installs. I've followed instruction for installation and migration and still got `"Unrecognized or legacy configuration settings found" npmScopes` after adding `npmScopes` in projects `.yarnrc.yml`

**Comment by merceyz** [comment]
Open a new issue with reproduction steps please

**Comment by Smbkilla** [comment]
Hi,

@merceyz I've opened a new [issue](https://github.com/yarnpkg/berry/issues/2430)

**Comment by rainkinz** [comment]
Similar to @maoueh `YARN_INTEGRITY_CHECK=false`. Running `unset YARN_INTEGRITY_CHECK` then `yarn set version stable` fixed it for me.

**Comment by alehander92** [comment]
similar: had to remove `yarn_enable_nixify` with `unset`. thank you!
