### ISSUE TITLE
`yarn set version 2.4.1` throws 404

### ISSUE THREAD

**Issue by sshquack** [yarnpkg/berry#2556]
## Related
https://github.com/yarnpkg/berry/issues/2514#issuecomment-789258058

## Issue
Currently on Yarn 2.4.0 and trying to update to Yarn 2.4.1 release (using https://yarnpkg.com/cli/set/version) so that I can upgrade to TS 4.2.2

```
❯ yarn set version 2.4.1          
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/%40yarnpkg/cli/2.4.1/packages/yarnpkg-cli/bin/yarn.js
➤ YN0001: HTTPError: Response code 404 (Not Found)
    at se.<anonymous> (/Users/om/Documents/work/eagleridge/.yarn/releases/yarn-2.4.0.cjs:23:10082)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
➤ YN0000: Failed with errors in 0s 807ms
```

Note that 2.4.0 works as expected
```
❯ yarn set version 2.4.0
➤ YN0000: Downloading https://github.com/yarnpkg/berry/raw/%40yarnpkg/cli/2.4.0/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-2.4.0.cjs
➤ YN0000: Done in 2s 447ms
```

Temporary workaround: `yarn set version berry` but it would be best to pin to a specific version than a tag.

**Comment by sshquack** [comment]
Hi @arcanis Looks like you already updated the `packages/yarnpkg-cli` to 2.4.1 in https://github.com/yarnpkg/berry/commit/bfe534b7b266f4cf50bb19ebf9624b7d81e28543 Could you please also tag it for `2.4.1` similar to the 2.4.0 tag https://github.com/yarnpkg/berry/tree/%40yarnpkg/cli%2F2.4.0

**Comment by arcanis** [comment]
Forgot to push the tags - should be fixed

**Comment by sshquack** [comment]
Works now. Thanks @arcanis

**Comment by ms2052001** [comment]
I am still having the same issue, my yarn version is `2.4.1`. I tried to copy the same [bin file](https://github.com/babel/babel/blob/main/.yarn/releases/yarn-2.4.1.cjs) using in babeljs.

Unfortunately, I still struggling with this weird issue.

```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ HTTPError: Response code 404 (Not Found)
    at se.<anonymous> (/home/ms/myp/arabi/arabi/.yarn/releases/yarn-2.4.1.cjs:23:10082)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
➤ YN0000: └ Completed in 2s 937ms
```

**Comment by ms2052001** [comment]
Alhamdulilah, I have just solved this problem, the problem was that I changed `enableTransparentWorkspaces` to true without changing the workspace packages protocol, e.g. `workspace:^1.2.3`. After I tried to install, this error came up to me. I suggest logging some more information about what is going in.

**Comment by merceyz** [comment]
@ms2052001 We will print better errors after https://github.com/yarnpkg/berry/pull/2406 is merged
