### ISSUE TITLE
[Bug?]: Not finding modules in Typescript import statements

### ISSUE THREAD

**Issue by imdavidmin** [yarnpkg/berry#3350]
### Self-service

- [ ] I'd be willing to implement a fix

### Describe the bug

Yarn VSCode SDK no longer working to find modules

### To reproduce

1.  Create new folder
2. `yarn set version berry`
3. `yarn init`
4. Create new file `index.ts`
5. `yarn add typescript -D`
6. write in `index.ts` `import React from 'react'`
7. `yarn add react`
8. `yarn dlx @yarnpkg/sdks vscode`
9. Set Typescript version in VSCode to 4.4.2-sdk

### Environment

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
  Binaries:
    Node: 14.17.4 - C:\Users\user\AppData\Local\Temp\xfs-f520d191\node.CMD
    Yarn: 3.0.1 - C:\Users\user\AppData\Local\Temp\xfs-f520d191\yarn.CMD
    npm: 7.11.1 - C:\Program Files\nodejs\npm.CMD

### Additional context

Yarn v3.0.1

**Comment by merceyz** [comment]
The fix has been released as `3.0.2` so you can now the following to fix it
```
yarn set version berry && yarn
```

**Comment by lamhungypl** [comment]
Unfortunately, this issue still occurs. 
I started a new `yarn create react-app my-app --template typescript` project, nothing work except  `yarn dev`

System:
OS: macOS 12.0.1
CPU: 2 GHz Quad-Core Intel Core i5
Node: 16.13.0
Yarn: 3.1.0

```javascript
package.json
{
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "serve": "vite preview",
    "prepare": "husky install"
  },
  "dependencies": {
    "antd": "^4.17.1",
    "react": "^17.0.0",
    "react-dom": "^17.0.0"
  },
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@vitejs/plugin-react": "^1.0.0",
    "eslint": "^8.2.0",
    "husky": "^7.0.4",
    "prettier": "^2.4.1",
    "typescript": "^4.3.2",
    "vite": "^2.6.4"
  },
  "lint-staged": {
    "*.js": "eslint --cache --fix",
    "*.{js,css,md}": "prettier --write"
  }
}


```

<img width="895" alt="Screen Shot 2021-11-24 at 15 59 48" src="https://user-images.githubusercontent.com/43105576/143207318-caf84174-bbb9-44e2-9e48-0ebaa8c2f3bf.png">

**Comment by merceyz** [comment]
@lamhungypl See https://github.com/yarnpkg/berry/issues/3722#issuecomment-974634888

**Comment by MAST1999** [comment]
> @lamhungypl See [#3722 (comment)](https://github.com/yarnpkg/berry/issues/3722#issuecomment-974634888)

Hey, I had the same problem but after using `yarn set version berry && yarn` I can build and run the project from the terminal but vscode keeps complaining that the modules or their types don't exist.
![image](https://user-images.githubusercontent.com/48868969/151854840-baf6ab2a-8d27-493e-9826-a6a3d28c2bf7.png)
I was wondering if I had missed something.
I also ran `yarn dlx @yarnpkg/sdks vscode`

Thanks for the hard work.

**Comment by shonsirsha** [comment]
> > @lamhungypl See [#3722 (comment)](https://github.com/yarnpkg/berry/issues/3722#issuecomment-974634888)
> 
> Hey, I had the same problem but after using `yarn set version berry && yarn` I can build and run the project from the terminal but vscode keeps complaining that the modules or their types don't exist. ![image](https://user-images.githubusercontent.com/48868969/151854840-baf6ab2a-8d27-493e-9826-a6a3d28c2bf7.png) I was wondering if I had missed something. I also ran `yarn dlx @yarnpkg/sdks vscode`
> 
> Thanks for the hard work.

Hi, did you find any solution for this?

**Comment by koistya** [comment]
@MAST1999 it should with Yarn v2 and PnP. Are you sure you have `@types/react` and `@types/react-dome` dependencies installed?

[GraphQL API and Relay Starter Kit](https://github.com/kriasoft/relay-starter-kit) → [`web/package.json#L53-L54`](https://github.com/kriasoft/relay-starter-kit/blob/71462f8c707200b81800c13063147e01799dc6e6/web/package.json#L53-L54)

**Comment by MAST1999** [comment]
@koistya 
Yeah I was sure. I even saw the packages in the cache and I had installed the needed extension mentioned in the docs.
But I still couldn't get vscode to recognize them.
I was on the version 3 BTW.
