### ISSUE TITLE
[Bug?]: Performance impact of `process.report.getReport()` is undesirable

### ISSUE THREAD

**Issue by oliversalzburg** [yarnpkg/berry#5167]
### Self-service

- [X] I'd be willing to implement a fix

### Describe the bug

Yarn calls `process.report.getReport` internally to retrieve a list of loaded shared libraries to determine the C library in use. This can be seen following the code path at <https://github.com/yarnpkg/berry/blob/26154331928793c8ab9b011790f5e3ca2f5d9e6d/packages/yarnpkg-core/sources/Project.ts#L736-L738>. The comment highlighted here already hints at the larger issue.

Yarn will grab this report and to generate the report, Node will go through all open handles in UV and retrieve information about them. Most importantly here, it will query information about all open socket handles. There handles are processed with <https://github.com/nodejs/node/blob/9eb363a3e00dbba572756c7ed314273f17ea8e2e/src/node_report_utils.cc#L12>.

- This function will try to resolve the name for at least the local IP address used on the socket (as I observed).
- This process is applied for all socket handles in series.
- This can potentially take minutes to fully generate.

As the above quoted comment implies, there is a larger issue on WSL. From my observations, WSL will, by default, register a very poor DNS resolver into the Linux distribution. This resolver is not only extremely slow, it also responds to all queries with an answer with a TTL of `0`. I expect that this causes the RDNS request for every single socket to go through the entire stack every single time.

While this behavior is generally prevented in yarn by calling out to the report generator early, when using plugins like `upgrade-interactive`, a lot of sockets have been opened from the resolution process and this causes a very long hang when the report is being generated. This approach seems unreliable. Determination of platform specifics should not be hindered by DNS performance.

### To reproduce

```js
const https = require("node:https");

const SOCKET_COUNT = 10;
const sockets = [];
let allResolved = false;

const keepAliveAgent = new https.Agent({ keepAlive: true });

const performRequest = () => {
  const socketPromise = new Promise((resolve) => {
    https
      .get(
        {
          agent: keepAliveAgent,
          hostname: "registry.npmjs.org",
        },
        () => {
          process.stdout.write(".");
          resolve();
        }
      )
      .on("error", (error) => {
        console.error(error);
        resolve();
      });
  });
  sockets.push(socketPromise);
};

process.stdout.write(`${new Date().toISOString()} opening ${SOCKET_COUNT} sockets`);
for (let loops = 0; loops < SOCKET_COUNT; ++loops) {
  performRequest();
}

Promise.all(sockets).then(() => {
  allResolved = true;
  console.log(
    `\n${new Date().toISOString()} all sockets created. requesting report...`
  );
  process.report.getReport();

  console.log(`${new Date().toISOString()} destroying client`);
  keepAliveAgent.destroy();

  console.log(`${new Date().toISOString()} end`);
});

const check = () => {
  if (!allResolved) {
    setTimeout(check, 200);
    return;
  }
};

check();
```

### Environment

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz
  Binaries:
    Node: 18.12.0 - /tmp/xfs-ec34c936/node
    Yarn: 1.22.19 - /tmp/xfs-ec34c936/yarn
    npm: 8.19.2 - /usr/local/bin/npm
```

### Additional context

This problem is amplified by poor WSL default behavior, but the underlying issue should apply generally.

**Comment by arcanis** [comment]
Very interesting investigation. I'm marking it as an external bug since I don't see a lot we can do on Yarn's side - ideally Node should provide a simpler API.

**Comment by oliversalzburg** [comment]
I also reported this on the Node side here: https://github.com/nodejs/node/issues/46060 and for WSL here https://github.com/microsoft/WSL/issues/9423

**Comment by edoardo-bluframe** [comment]
As @arty-name reported this bug is causing #4327 which is making `yarn berry` really difficult to use for a few of us. Over 2m - for some more - every time we install packages! Just FYI :smile:

**Comment by tadayosi** [comment]
Is there any workaround until the fix is provided?  Since `yarn install` is the most essential part of the tool :frowning_face:

**Comment by lpic10** [comment]
maybe this can help: https://github.com/nodejs/node/issues/46060#issuecomment-1808070936

**Comment by arcanis** [comment]
Can you try the 4.0.2 (literally just released)? It includes a workaround to avoid paying the `getReport` cost.

**Comment by arty-name** [comment]
Yes! Yarn is fast again! :heart_eyes:

**Comment by arty-name** [comment]
Uhm, in case the overt emotions in my previous comments obscure its meaning, let me state that I have tested yarn 4.0.2 and the workaround in https://github.com/yarnpkg/berry/commit/ffc9f8ad2b8f018d050632f6168392adb4508c2a has resolved the issue for me. Thank you @arcanis!

**Comment by oliversalzburg** [comment]
From my side, I feel like this issue has been resolved on the WSL distribution/platform level. The performance is as expected, even with the WSL-internal DNS resolver and even with pre-4.0.2.

Thus, I'd like to close this issue. Non-WSL-related performance issues with `getReport` should likely go into separate issues.

That being said, nice to see that the report is no longer required 😊

**Comment by tadayosi** [comment]
Thanks. I tried 4.0.2 but unfortunately this doesn't solve my problem of `yarn install` slowness. Probably mine is a different problem from the original one.

**Comment by Tofandel** [comment]
You need to set `process.report.excludeNetwork = true` before getReport to fix the speed issue of get report https://github.com/yarnpkg/berry/blob/f59bbf9f3828865c14b06a3e5cc3ae284a0db78d/packages/yarnpkg-core/sources/nodeUtils.ts#L49

See https://github.com/lovell/detect-libc/pull/21
